name: windows-make-installer

on:
  workflow_run:
    workflows: ["Pylint"]
    types:
      - completed
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'
    

jobs:
  Windows-Installer:
    permissions:
      contents: write
      
    runs-on: windows-latest
    steps: 

      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Make enviromment Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PyInstaller
        run: python -m pip install pyinstaller

      - name: Building exe with PyInstaller
        run: | 
          python -m PyInstaller setup.py --name zork++

      - name: Building the installer
        run: |
          "%programfiles(x86)%\Inno Setup 6\iscc.exe" ".\release-config\windows-installer-zork.iss"
        shell: cmd

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - run: |
          ls
      - name: Make Zip
        run: |
          7z a windows-installer.zip zork-installer.exe

      - name: upload windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: windows-installer.zip
          asset_name: windows-installer.zip
          asset_content_type: application/zip
        